spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      authentication-database: admin
      security:
        authorization: enabled

server:
  port: 8088